# Languages
#   Create a `[X]` block for each language you want, where X is the language ID.
#   Refer to https://sourcethemes.com/academic/docs/language/

# Configure the Spanish version of the site.
[es]
  languageCode = "es-pa"
   contentDir = "content/es"

# Configure the English version of the site.
[en]
  languageCode = "en-us"
  contentDir = "content/en"
  title = "Website in english..."
  [en.params]
    description = "Site description in Englsih..."
  [[enh.menu.main]]
    name = "About"
    url = "#about"
    weight = 1
